server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biz?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false

logging:
  path: E:/IdeaProjects/logs/biz
  pattern:
    console: '%date{HH:mm:ss.SSS} %highlight(%-5p) [%t] %C{0}.%M:%L %msg%xEx%n'
    file: '%date{HH:mm:ss.SSS} %-5p [%t] %C{0}.%M:%L %msg%xEx%n'
  level:
    org.hibernate.SQL: DEBUG
    com.niu: DEBUG