server.port: 8080


spring:
  datasource:
      url: jdbc:mysql://d0blriydbi.mysql.dbdev.dsfdc.com:5008/biz?useUnicode=yes&characterEncoding=UTF8&useSSL=false
      username: deployop
      password: DDeployop88#
  thymeleaf:
    cache: false

logging:
  path: E:/IdeaProjects/logs/biz
  pattern:
    console: '%date{HH:mm:ss.SSS} %highlight(%-5p) [%t] %C{0}.%M:%L %msg%xEx%n'
    file: '%date{HH:mm:ss.SSS} %-5p [%t] %C{0}.%M:%L %msg%xEx%n'
  level:
    org.hibernate.SQL: DEBUG
    com.niu: DEBUG